base_url = "https://slightknack.dev"
title = "Isaac Clayton"
author = "Isaac Clayton"
description = "A cozy little corner of the web."
generate_feeds = true
compile_sass = false
# build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "boron"          # "material-dark" "gray-matter-dark"
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true

[search]

[extra]
# Put all your custom variables here
